# This file is used for development.
# See .devcontainer directory.

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client
